// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// generate_sg_pairs_int
IntegerMatrix generate_sg_pairs_int(const IntegerVector& c_labels, const IntegerVector& r_labels);
RcppExport SEXP _spARI_generate_sg_pairs_int(SEXP c_labelsSEXP, SEXP r_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type c_labels(c_labelsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type r_labels(r_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_sg_pairs_int(c_labels, r_labels));
    return rcpp_result_gen;
END_RCPP
}
// generate_gs_pairs_int
IntegerMatrix generate_gs_pairs_int(const IntegerVector& c_labels, const IntegerVector& r_labels);
RcppExport SEXP _spARI_generate_gs_pairs_int(SEXP c_labelsSEXP, SEXP r_labelsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerVector& >::type c_labels(c_labelsSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type r_labels(r_labelsSEXP);
    rcpp_result_gen = Rcpp::wrap(generate_gs_pairs_int(c_labels, r_labels));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spARI_generate_sg_pairs_int", (DL_FUNC) &_spARI_generate_sg_pairs_int, 2},
    {"_spARI_generate_gs_pairs_int", (DL_FUNC) &_spARI_generate_gs_pairs_int, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_spARI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
