# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

generate_sg_pairs_int <- function(c_labels, r_labels) {
    .Call(`_spARI_generate_sg_pairs_int`, c_labels, r_labels)
}

generate_gs_pairs_int <- function(c_labels, r_labels) {
    .Call(`_spARI_generate_gs_pairs_int`, c_labels, r_labels)
}

